replicaCount: 5

image:
  repository: ghcr.io/bcgov/sso
  tag: v7.5-9-build.4
  pullPolicy: Always

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi

postgres:
  host: sso-patroni
  port: 5432

maintenancePage:
  enabled: true
  active: false

patroni:
  replicaCount: 2
  # credentials:
  #   existingSecret: false
  #   superuser:
  #     username: postgres
  #     password:
  #   admin:
  #     username: admin
  #     password:
  #   standby:
  #     username: standby
  #     password:

  # additionalCredentials:
  #   - username: ssokeycloak
  #     password:
  persistentVolume:
    size: 1.7Gi

  podDisruptionBudget:
    enabled: false
