apiVersion: v1
name: kc-cron-job
description: 'Helm chart for CronJob to collect Keycloak active sessions'
version: 0.3.0
dependencies:
  - name: patroni
    version: 1.5.1
    repository: https://bcgov.github.io/sso-helm-charts
